spring.application.name=social-media-app
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/social_media_db
spring.datasource.username=social
spring.datasource.password=social
spring.jpa.show-sql=true

